<?xml version="1.0" encoding="utf-8"?>
<!-- Poprawiona nakladka ROT_Hideouts v1.2.11 (Jeff/Claude 17.09.2026). Oryginal celowal w Hideout[@id]/@scene_name,
     a mapa ROT trzyma scene w Locations/Location[@id=hideout_center]/@scene_name - zaden szablon nie trafial i wszystkie
     266 kryjowek zostawaly na scenach vanilla. Tu: te same przypisania autora, cel poprawiony; sceny vanilla w wersji _sv
     (tak jak mapa); przypisania do scen, ktorych nie ma w zadnym module, pominiete (kryjowka zostaje jak na mapie). -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:template match="@*|node()"><xsl:copy><xsl:apply-templates select="@*|node()"/></xsl:copy></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_10']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_11']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_12']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">desert_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_13']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_14']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_16']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_17']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_19']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_21']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_24']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_25']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_26']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_28']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_29']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">desert_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_30']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_31']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">desert_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_32']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_33']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">desert_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_34']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">desert_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">desert_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_7']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_desert_9']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_12']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_14']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_15']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_16']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_17']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_18']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_20']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_23']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_24']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_26']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_27']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_28']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_29']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_30']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_31']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_32']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_33']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_34']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_35']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_36']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_37']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_38']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_39']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_4']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_40']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_41']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_43']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_44']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_45']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_46']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_47']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_b_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_48']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_49']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_51']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_52']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_53']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_57']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_59']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_63']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_65']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_69']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_7']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_77']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_8']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_80']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_81']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_83']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_84']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_85']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_b_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_86']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_87']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_forest_9']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_kingswood_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_kingswood_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_kingswood_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_10']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_11']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_12']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_13']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_14']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_15']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_16']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_17']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_18']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_19']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_20']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_21']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_22']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_23']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_24']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_25']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_27']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_28']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_29']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_30']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_31']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_32']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_34']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_35']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_36']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_37']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_38']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_39']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_4']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_40']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_41']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_42']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_43']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_44']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_45']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_46']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_49']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_52']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_53']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_55']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_56']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_57']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_58']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_7']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_mountain_8']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">mountain_hideout_002_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_10']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_11']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_4']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_7']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_8']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_robber_9']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_10']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_11']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_12']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_13']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_14']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_15']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_16']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_17']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_18']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_19']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_20']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_21']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_23']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_24']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_25']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_26']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_27']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_28']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_29']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_30']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_31']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_33']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_34']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_35']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_37']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_39']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_4']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_40']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_41']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_42']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_44']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_45']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_46']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_47']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_48']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_49']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Myscenehideout</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_50']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_51']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_52']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_54']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_55']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_56']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_57']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_58']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_59']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">RuinSeaside</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_60']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_61']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_62']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_63']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">contest_shipwreck_cove</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_64']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_65']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_66']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">OldVlandiaTown</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_67']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_7']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">scn_smugglersdescent1</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_seaside_9']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_b_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_10']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_12']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_13']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_15']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_16']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">hideout_steppe_001_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_17']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">hideout_steppe_001_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_18']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_19']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_21']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">hideout_steppe_001_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_22']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">hideout_steppe_001_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_24']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_25']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_4']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">hideout_steppe_001_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_7']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_steppe_9']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Levente</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_yiti_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_yiti_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Canyon</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_yiti_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Scene_Ceftadzime</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_yiti_4']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_yiti_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='hideout_yiti_6']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">patatest</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='skagosi_hideout_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">sea_bandit_c_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='wight_hideout_1']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='wight_hideout_12']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">Ruins_of_Erandel</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='wight_hideout_2']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_hideout_004_sv</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='wight_hideout_3']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">forest_complete</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='wight_hideout_5']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">battanian_burial_mound</xsl:attribute></xsl:template>
  <xsl:template match="Settlement[@id='wight_hideout_9']/Locations/Location[@id='hideout_center']/@scene_name"><xsl:attribute name="scene_name">battanian_burial_mound</xsl:attribute></xsl:template>
</xsl:stylesheet>
