<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>ForgeView</AssemblyName>
    <RootNamespace>ForgeView</RootNamespace>
    <Configuration>Release</Configuration>
    <DebugType>none</DebugType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup><Compile Include="src\**\*.cs" /></ItemGroup>
  <ItemGroup>
    <Reference Include="BannerKings"><HintPath>$(GameLibs)/BannerKings.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Bannerlord.UIExtenderEx"><HintPath>$(GameLibs)/Bannerlord.UIExtenderEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameLibs)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.CampaignSystem"><HintPath>$(GameLibs)/TaleWorlds.CampaignSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Core"><HintPath>$(GameLibs)/TaleWorlds.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Core.ViewModelCollection"><HintPath>$(GameLibs)/TaleWorlds.Core.ViewModelCollection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Library"><HintPath>$(GameLibs)/TaleWorlds.Library.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Localization"><HintPath>$(GameLibs)/TaleWorlds.Localization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.ObjectSystem"><HintPath>$(GameLibs)/TaleWorlds.ObjectSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.MountAndBlade"><HintPath>$(GameLibs)/TaleWorlds.MountAndBlade.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Engine"><HintPath>$(GameLibs)/TaleWorlds.Engine.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
