<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Armoury</AssemblyName>
    <RootNamespace>Armoury</RootNamespace>
    <Configuration>Release</Configuration>
    <DebugType>none</DebugType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="src\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MCMv5"><HintPath>$(GameLibs)/MCMv5.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(GameLibs)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.CampaignSystem"><HintPath>$(GameLibs)/TaleWorlds.CampaignSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Core"><HintPath>$(GameLibs)/TaleWorlds.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Library"><HintPath>$(GameLibs)/TaleWorlds.Library.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Localization"><HintPath>$(GameLibs)/TaleWorlds.Localization.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection"><HintPath>$(GameLibs)/TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Core.ViewModelCollection"><HintPath>$(GameLibs)/TaleWorlds.Core.ViewModelCollection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.InputSystem"><HintPath>$(GameLibs)/TaleWorlds.InputSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.ObjectSystem"><HintPath>$(GameLibs)/TaleWorlds.ObjectSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.DotNet"><HintPath>$(GameLibs)/TaleWorlds.DotNet.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Engine"><HintPath>$(GameLibs)/TaleWorlds.Engine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.MountAndBlade"><HintPath>$(GameLibs)/TaleWorlds.MountAndBlade.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.SaveSystem"><HintPath>$(GameLibs)/TaleWorlds.SaveSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Engine"><HintPath>$(GameLibs)/TaleWorlds.Engine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.ScreenSystem"><HintPath>$(GameLibs)/TaleWorlds.ScreenSystem.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.GauntletUI"><HintPath>$(GameLibs)/TaleWorlds.GauntletUI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.GauntletUI.Data"><HintPath>$(GameLibs)/TaleWorlds.GauntletUI.Data.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Engine.GauntletUI"><HintPath>$(GameLibs)/TaleWorlds.Engine.GauntletUI.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.Core.ViewModelCollection"><HintPath>$(GameLibs)/TaleWorlds.Core.ViewModelCollection.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="TaleWorlds.CampaignSystem.ViewModelCollection"><HintPath>$(GameLibs)/TaleWorlds.CampaignSystem.ViewModelCollection.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
